<cfsetting enableCfoutputOnly="true">

<cfscript>
	flashMessagesBootstrapMeta = {};
	flashMessagesBootstrapMeta.version = "1.0.2";
	flashInsert(info="flash(""info"")");
	flashInsert(success="flash(""success"")");
	flashInsert(warning="flash(""warning"")");
	flashInsert(danger="flash(""danger"")");
	flashInsert(error="flash(""error"")");
	flashInsert(customKey="flash(""customKey"")");
</cfscript>
<!---<cfinclude template="stylesheets/bootstrap.min.cfm">--->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	
<cfoutput>

<h1>flashMessages Bootstrap v#flashMessagesBootstrapMeta.version#</h1>
<p>
	This plugin modifies the built in markup generated by flashMessages() to use Bootstrap Alerts.
</p>

<h2>Usage/Examples</h2>
<p>
	<ul>
		<li>If the flash key name is one of the sandard <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> Alert types of<em>info</em>, <em>success</em>, <em>warning</em>, or <em>danger</em>, a <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> compatible class of either <em>alert-info</em>, <em>alert-success</em>, <em>alert-warning</em>, or <em>alert-danger</em> will be used to create the markup block according to the flash key name.</li>
		<li>In addition to the standard <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> Alert types mentioned above, this plugin also will look for a Flash key of <em>error</em> and convert that to a <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> class of <em>alert-danger</em>.</li>
		<li>This plugin also has a catch all wildcard feature that will convert any other remainig Flash key not handled by the cases above to the standard <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> class of <em>alert-info</em>.</li>
	</ul>
	#flashMessages()#
</p>

<h2>Configuration</h2>
<p>
	Simply install this plug in by copying the zip file into the plugins folder or via CommandBox. The only other requirement is to 
	properly setup <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>. Below is an example of a layout.cfm file with
	the appropriate <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> elements added in.
</p>
<pre>
&lt;!--- Place HTML here that should be used as the default layout of your application. ---&gt;
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
  &lt;head&gt;
    &lt;meta charset="utf-8"&gt;
    &lt;meta http-equiv="X-UA-Compatible" content="IE=edge"&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1"&gt;
    &lt;!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags --&gt;
    &lt;cfoutput&gt;#csrfMetaTags()#&lt;/cfoutput&gt;

    &lt;!-- Bootstrap --&gt;
	&lt;!-- Latest compiled and minified CSS --&gt;
	&lt;link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"&gt;

	&lt;!-- Optional theme --&gt;
	&lt;link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"&gt;

    &lt;!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --&gt;
    &lt;!-- WARNING: Respond.js doesn't work if you view the page via file:// --&gt;
    &lt;!--[if lt IE 9]&gt;
      &lt;script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"&gt;&lt;/script&gt;
      &lt;script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
  &lt;/head&gt;
  &lt;body&gt;
		&lt;cfoutput&gt;
		##flashMessages()##
		##includeContent()##
		&lt;/cfoutput&gt;

	    &lt;!-- jQuery (necessary for Bootstrap's JavaScript plugins) --&gt;
	    &lt;script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"&gt;&lt;/script&gt;
	    &lt;!-- Include all compiled plugins (below), or include individual files as needed --&gt;
		&lt;!-- Latest compiled and minified JavaScript --&gt;
		&lt;script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"&gt;&lt;/script&gt;    
  &lt;/body&gt;
&lt;/html&gt;
</pre>

<h2>Uninstallation</h2>
<p>
	To uninstall this plugin, simply delete the <tt>/plugins/FlashMessagesBootstrap-#flashMessagesBootstrapMeta.version#.zip</tt> file.
</p>

<h2>Credits</h2>
<p>
	This plugin was created by <a href="https://github.com/bpamiri">Peter Amiri</a>. To submit an issue or fork this plugin, visit the <a href="https://github.com/bpamiri/cfwheels-flashmessages-bootstrap">https://github.com/bpamiri/cfwheels-flashmessages-bootstrap</a> repository on GitHub.
</p>

</cfoutput>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>    

<cfsetting enableCfoutputOnly="false">
